name       : certbot
version    : 0.27.1
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/c/certbot/certbot-0.27.1.tar.gz : 3570bd14ed223c752f309dbd082044bd9f11a339d21671e70a2eeae4e51ed02a
license    : Apache-2.0
component  : security.crypto
summary    : A free, automated certificate authority client
description: |
    Certbot, previously the Let's Encrypt Client, is EFF's tool to obtain certs from Let's Encrypt, and (optionally) auto-enable HTTPS on your server. It can also act as a client for any other CA that uses the ACME protocol.
builddeps  :
    - python-acme
    - python-configargparse
    - python-ipaddress
    - python-ndg-httpsclient
    - python-parsedatetime
    - python-pytest
    - python-zope.component
rundeps    :
    - python-acme
    - python-configargparse
    - python-configobj
    - python-ipaddress
    - python-ndg-httpsclient
    - python-parsedatetime
    - python-psutil
    - python-zope.component
build      : |
    %python_setup
install    : |
    %python_install
check      : |
    %python_test py.test -v
