name       : certbot
version    : 0.24.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/c/certbot/certbot-0.24.0.tar.gz : a072d4528bb3ac4184f5c961a96931795ddfe4b7cb0f3a98954bdd4cce5f6d70
license    : Apache-2.0
component  : security.crypto
summary    : A tool to automatically receive and install X.509 certificates to enable TLS on servers. The client will interoperate with the Let’s Encrypt CA which will be issuing browser-trusted certificates
    for free.
description: |
    Certbot, previously the Let's Encrypt Client, is EFF's tool to obtain certs from Let's Encrypt, and (optionally) auto-enable HTTPS on your server. It can also act as a client for any other CA that uses the ACME protocol.
builddeps  :
    - python-acme
    - python-configargparse
    - python-ipaddress
    - python-ndg-httpsclient
    - python-parsedatetime
    - python-zope.component
rundeps    :
    - python-acme
    - python-configargparse
    - python-configobj
    - python-ipaddress
    - python-ndg-httpsclient
    - python-parsedatetime
    - python-psutil
    - python-zope.component
build      : |
    %python_setup
install    : |
    %python_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        python setup.py test
    popd
