name       : certbot
version    : 0.18.2
release    : 1
source     :
    - https://github.com/certbot/certbot/archive/v0.18.2.tar.gz : c8a94e3e2dfa8efa379912a8dc67f561cf6daf7d8e13dbb76b40a38cfb40c08d
license    : Apache-2.0
component  : security.crypto
summary    : A tool to automatically receive and install X.509 certificates to enable TLS on servers. The client will interoperate with the Let’s Encrypt CA which will be issuing browser-trusted certificates for free.
description: |
    Certbot, previously the Let's Encrypt Client, is EFF's tool to obtain certs from Let's Encrypt, and (optionally) auto-enable HTTPS on your server. It can also act as a client for any other CA that uses the ACME protocol.
builddeps  :
    - python-setuptools
rundeps    :
    - python-acme
    - python-configargparse
    - python-configobj
    - python-cryptography
    - python-ipaddress
    - python-openssl
    - python-mock
    - python-ndg-httpsclient
    - python-parsedatetime
    - python-psutil
    - python-pyrfc3339
    - python-pytz
    - python-requests
    - python-setuptools
    - python-six
    - python-zope.interface
    - python-zope.component
build      : |
    %python_setup
install    : |
    %python_install
