name       : certbot
version    : 0.26.1
release    : 6
source     :
    - https://files.pythonhosted.org/packages/5e/f7/a8c8af1e8942f7ae2e3a5915118de7e446e2cfcef1444387c4f82b81ad82/certbot-0.26.1.tar.gz : 4983513d63f7f36e24a07873ca2d6ea1c0101aa6cb1cd825cda02ed520f6ca66
license    : Apache-2.0
component  : security.crypto
summary    : A free, automated certificate authority client
description: |
    Certbot, previously the Let's Encrypt Client, is EFF's tool to obtain certs from Let's Encrypt, and (optionally) auto-enable HTTPS on your server. It can also act as a client for any other CA that uses the ACME protocol.
builddeps  :
    - python-acme
    - python-configargparse
    - python-ipaddress
    - python-ndg-httpsclient
    - python-parsedatetime
    - python-pytest
    - python-zope.component
rundeps    :
    - python-acme
    - python-configargparse
    - python-configobj
    - python-ipaddress
    - python-ndg-httpsclient
    - python-parsedatetime
    - python-psutil
    - python-zope.component
build      : |
    %python_setup
install    : |
    %python_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        PYTHONPATH=$PWD py.test -v
    popd
