name       : certbot
version    : 1.0.0
release    : 19
source     :
    - https://pypi.python.org/packages/source/c/certbot/certbot-1.0.0.tar.gz : 86b82d31db19fffffb0d6b218951e2121ef514e3ff659aa042deaf92a33e302a
license    : Apache-2.0
component  : security.crypto
summary    : A free, automated certificate authority client
description: |
    Certbot, previously the Let's Encrypt Client, is EFF's tool to obtain certs from Let's Encrypt, and (optionally) auto-enable HTTPS on your server. It can also act as a client for any other CA that uses the ACME protocol.
builddeps  :
    - python-acme
    - python-configargparse
    - python-distro
    - python-ndg-httpsclient
    - python-parsedatetime
    - python-pytest
    - python-zope.component
rundeps    :
    - python-acme
    - python-configargparse
    - python-distro
    - python-configobj
    - python-ndg-httpsclient
    - python-parsedatetime
    - python-psutil
    - python-zope.component
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v
