name       : certbot
version    : 0.19.0
release    : 2
source     :
    - https://github.com/certbot/certbot/archive/v0.19.0.tar.gz : 164b496cc111f19619da1eac9e3fe03baac5ad5a97c2fa19eeffe07273c4b723
license    : Apache-2.0
component  : security.crypto
summary    : A tool to automatically receive and install X.509 certificates to enable TLS on servers. The client will interoperate with the Let’s Encrypt CA which will be issuing browser-trusted certificates for free.
description: |
    Certbot, previously the Let's Encrypt Client, is EFF's tool to obtain certs from Let's Encrypt, and (optionally) auto-enable HTTPS on your server. It can also act as a client for any other CA that uses the ACME protocol.
builddeps  :
    - python-acme
    - python-configargparse
    - python-cryptography
    - python-ipaddress
    - python-mock
    - python-ndg-httpsclient
    - python-openssl
    - python-parsedatetime
    - python-pyrfc3339
    - python-pytz
    - python-setuptools
    - python-zope.component
rundeps    :
    - python-acme
    - python-configargparse
    - python-configobj
    - python-cryptography
    - python-ipaddress
    - python-openssl
    - python-mock
    - python-ndg-httpsclient
    - python-parsedatetime
    - python-psutil
    - python-pyrfc3339
    - python-pytz
    - python-requests
    - python-setuptools
    - python-six
    - python-zope.interface
build      : |
    %python_setup
install    : |
    %python_install
check      : |
    %python_setup test
