name       : certbot
version    : 0.33.1
release    : 13
source     :
    - https://pypi.python.org/packages/source/c/certbot/certbot-0.33.1.tar.gz : d5203f32c50f3ec5a32df97e4affddbcd288a569678ecb5669adda21cd5ac3d9
license    : Apache-2.0
component  : security.crypto
summary    : A free, automated certificate authority client
description: |
    Certbot, previously the Let's Encrypt Client, is EFF's tool to obtain certs from Let's Encrypt, and (optionally) auto-enable HTTPS on your server. It can also act as a client for any other CA that uses the ACME protocol.
builddeps  :
    - python-acme
    - python-configargparse
    - python-ndg-httpsclient
    - python-parsedatetime
    - python-pytest
    - python-zope.component
rundeps    :
    - python-acme
    - python-configargparse
    - python-configobj
    - python-ndg-httpsclient
    - python-parsedatetime
    - python-psutil
    - python-zope.component
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v
